modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="autoattack"
version="1.0.0"
displayName="Auto Attack"
description="Auto attack when holding left click"
authors="SuddenlyScream"

[[dependencies.autoattack]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.autoattack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"